# Generated by Django 5.1 on 2026-02-04 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/dogs/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='woof.dogs')),
            ],
            options={
                'verbose_name': 'Dog photo',
                'verbose_name_plural': 'Dog photos',
                'ordering': ['order'],
            },
        ),
    ]
