# Generated by Django 4.2.2 on 2023-07-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0003_alter_profile_article_count_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='article_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
