# Generated by Django 5.1 on 2026-02-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0005_rename_content_dogs_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogs',
            name='lifespan',
        ),
        migrations.AddField(
            model_name='dogs',
            name='life_expectancy',
            field=models.CharField(blank=True, max_length=255, verbose_name='Life expectancy'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='activity_level',
            field=models.CharField(choices=[('calm', 'Calm (low energy)'), ('regular', 'Regular exercise (daily walks)'), ('high', 'Needs lots of activity'), ('energetic', 'Very energetic (high endurance)')], default='calm', max_length=15, verbose_name='Activity level'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='barking_level',
            field=models.CharField(choices=[('necessary', 'When necessary (rare, purposeful)'), ('infrequent', 'Infrequent (occasional barking)'), ('medium', 'Medium (regular alert barking)'), ('frequent', 'Frequent (barks often)'), ('vocal', 'Very vocal (howls, talks, barks)')], default='necessary', max_length=20, verbose_name='Barking level'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='family_friendliness',
            field=models.CharField(choices=[('low', 'Low (better with adults, limited tolerance)'), ('medium', 'Medium (family-oriented, needs supervision)'), ('high', 'High (affectionate, good with family)'), ('excellent', 'Excellent (very gentle, great with kids)')], default='medium', max_length=10, verbose_name='Family friendliness'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='hypoallergenic',
            field=models.CharField(choices=[('no', 'No (not hypoallergenic)'), ('low', 'Low (sheds a lot)'), ('moderate', 'Moderate (some shedding)'), ('high', 'High (minimal shedding)')], default='no', max_length=10, verbose_name='Hypoallergenic'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='trainability',
            field=models.CharField(choices=[('independent', 'Independent (thinks for itself)'), ('stubborn', 'May be stubborn (needs patience)'), ('agreeable', 'Agreeable (trainable)'), ('eager', 'Eager to please (quick learner)'), ('easy', 'Easy training (very easy to train)')], default='independent', max_length=15, verbose_name='Trainability'),
        ),
    ]
