# Generated by Django 5.1 on 2024-08-17 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0005_dogs_care_dogs_coat_type_dogs_living_conditions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='dogs',
            options={'ordering': ['id'], 'verbose_name': 'Dog breed', 'verbose_name_plural': 'Dog breeds'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='care',
            field=models.TextField(blank=True, verbose_name='Care'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='woof.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='coat_type',
            field=models.CharField(choices=[('smooth', 'Smooth-haired'), ('curly', 'Curly'), ('long', 'Long-haired'), ('fluffy', 'Fluffy'), ('hairless', 'Hairless')], default='smooth', max_length=10, verbose_name='Coat type'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='content',
            field=models.TextField(blank=True, verbose_name='Brief description'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='living_conditions',
            field=models.TextField(blank=True, verbose_name='Living conditions'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=10, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time created'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Time update'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Dog breed'),
        ),
    ]
