# Generated by Django 5.1 on 2026-02-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0006_remove_dogs_lifespan_dogs_life_expectancy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='trainability',
            field=models.CharField(choices=[('independent', 'Independent (thinks for itself)'), ('stubborn', 'May be stubborn (patience)'), ('agreeable', 'Agreeable (trainable)'), ('eager', 'Eager to please (quick learner)'), ('easy', 'Easy training (very easy to train)')], default='independent', max_length=15, verbose_name='Trainability'),
        ),
    ]
