# Generated by Django 5.1 on 2024-08-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0006_alter_category_options_alter_dogs_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('smooth', 'Smooth-haired'), ('curly', 'Curly'), ('long', 'Long-haired'), ('fluffy', 'Fluffy'), ('hairless', 'Hairless')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='dogs',
            name='coat_type',
        ),
        migrations.AlterField(
            model_name='dogs',
            name='content',
            field=models.TextField(blank=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='living_conditions',
            field=models.TextField(blank=True, verbose_name='Conditions'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Breed'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='coat_types',
            field=models.ManyToManyField(blank=True, to='woof.coattype', verbose_name='Coat types'),
        ),
    ]
