# Generated by Django 5.1 on 2024-08-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0007_coattype_remove_dogs_coat_type_alter_dogs_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogs',
            name='coat_types',
        ),
        migrations.AddField(
            model_name='dogs',
            name='coat_type',
            field=models.CharField(choices=[('smooth', 'Smooth-haired'), ('curly', 'Curly'), ('long', 'Long-haired'), ('fluffy', 'Fluffy'), ('hairless', 'Hairless')], default='smooth', max_length=10, verbose_name='Coat type'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Вreed'),
        ),
    ]
