# Generated by Django 5.1.15 on 2026-04-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0008_section_dogs_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country / Region of origin'),
        ),
    ]
