# Generated by Django 5.1 on 2024-08-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0009_alter_coattype_name_alter_dogs_coat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='size',
            field=models.CharField(choices=[('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('giant', 'Giant')], default='small', max_length=10, verbose_name='Size'),
        ),
    ]
