# Generated by Django 5.1 on 2024-08-23 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0010_alter_dogs_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogs',
            options={'ordering': ['title'], 'verbose_name': 'Dog breed', 'verbose_name_plural': 'Dog breeds'},
        ),
        migrations.AddField(
            model_name='dogs',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coattype',
            name='name',
            field=models.CharField(choices=[('curly', 'Curly'), ('double', 'Double Coat'), ('fluffy', 'Fluffy'), ('hairless', 'Hairless'), ('long', 'Long-haired'), ('rough', 'Rough-haired'), ('silky', 'Silky'), ('smooth', 'Smooth-haired'), ('wire', 'Wire-haired')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='woof.category', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='coat_type',
            field=models.CharField(choices=[('curly', 'Curly'), ('double', 'Double Coat'), ('fluffy', 'Fluffy'), ('hairless', 'Hairless'), ('long', 'Long-haired'), ('rough', 'Rough-haired'), ('silky', 'Silky'), ('smooth', 'Smooth-haired'), ('wire', 'Wire-haired')], default='smooth', max_length=10, verbose_name='Coat type'),
        ),
    ]
