# Generated by Django 5.1 on 2024-08-23 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0011_alter_dogs_options_dogs_user_alter_coattype_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogs',
            name='user',
        ),
    ]
