# Generated by Django 5.1 on 2024-08-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0012_remove_dogs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='user_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='User Email'),
        ),
    ]
