# Generated by Django 5.1.15 on 2026-04-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0012_alter_dogs_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='varieties',
            field=models.CharField(blank=True, max_length=255, verbose_name='Varieties'),
        ),
    ]
