# Generated by Django 5.1 on 2024-08-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0013_dogs_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='activity_level',
            field=models.CharField(choices=[('high', 'Needs Lots Of Activity'), ('regular', 'Regular Exercise'), ('energetic', 'Energetic'), ('calm', 'Calm')], default='regular', max_length=10, verbose_name='Activity Level'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='trainability',
            field=models.CharField(choices=[('easy', 'Easy Training'), ('stubborn', 'May Be Stubborn'), ('agreeable', 'Agreeable'), ('eager', 'Eager To Please'), ('independent', 'Independent')], default='easy', max_length=11, verbose_name='Trainability'),
        ),
        migrations.AlterField(
            model_name='coattype',
            name='name',
            field=models.CharField(choices=[('curly', 'Curly'), ('wavy', 'Wavy'), ('rough', 'Rough-haired'), ('corded', 'Corded'), ('hairless', 'Hairless'), ('short', 'Short-haired'), ('medium', 'Medium-haired'), ('long', 'Long-haired'), ('smooth', 'Smooth-haired'), ('wiry', 'Wiry'), ('silky', 'Silky'), ('double', 'Double Coat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='coat_type',
            field=models.CharField(choices=[('curly', 'Curly'), ('wavy', 'Wavy'), ('rough', 'Rough-haired'), ('corded', 'Corded'), ('hairless', 'Hairless'), ('short', 'Short-haired'), ('medium', 'Medium-haired'), ('long', 'Long-haired'), ('smooth', 'Smooth-haired'), ('wiry', 'Wiry'), ('silky', 'Silky'), ('double', 'Double Coat')], default='smooth', max_length=10, verbose_name='Coat type'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='size',
            field=models.CharField(choices=[('xsmall', 'XSmall'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'XLarge')], default='small', max_length=10, verbose_name='Size'),
        ),
    ]
