# Generated by Django 5.1.15 on 2026-05-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0014_alter_dogs_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to='groups/', verbose_name='Group image'),
        ),
    ]
