# Generated by Django 5.1 on 2024-08-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0015_category_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_visible',
        ),
    ]
