# Generated by Django 5.1 on 2024-08-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0016_remove_category_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='activity_level',
            field=models.CharField(choices=[('calm', 'Calm'), ('regular', 'Regular Exercise'), ('high', 'Needs Lots Of Activity'), ('energetic', 'Energetic')], default='calm', max_length=10, verbose_name='Activity Level'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='coat_type',
            field=models.CharField(choices=[('curly', 'Curly'), ('wavy', 'Wavy'), ('rough', 'Rough-haired'), ('corded', 'Corded'), ('hairless', 'Hairless'), ('short', 'Short-haired'), ('medium', 'Medium-haired'), ('long', 'Long-haired'), ('smooth', 'Smooth-haired'), ('wiry', 'Wiry'), ('silky', 'Silky'), ('double', 'Double Coat')], default='cirly', max_length=10, verbose_name='Coat type'),
        ),
    ]
