# Generated by Django 5.2.17 on 2026-08-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0016_alter_category_options_category_fci_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='desc_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='care_en',
            field=models.TextField(blank=True, null=True, verbose_name='Care'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='care_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Care'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='colors_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Colors'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='colors_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Colors'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='country_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country / Region of origin'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='country_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country / Region of origin'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='height_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='height_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='life_expectancy_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Life expectancy'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='life_expectancy_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Life expectancy'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='living_conditions_en',
            field=models.TextField(blank=True, null=True, verbose_name='Conditions'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='living_conditions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Conditions'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='photo_author_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Main photo author'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='photo_author_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Main photo author'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='summary_en',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='summary_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Breed'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Breed'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='varieties_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Varieties'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='varieties_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Varieties'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='weight_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='weight_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='section',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='section',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Section'),
        ),
    ]
