# Generated by Django 5.2.17 on 2026-08-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0017_category_desc_en_category_desc_ru_category_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coatlength',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coatlength',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coattype',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coattype',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
