# Generated by Django 5.1 on 2024-08-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0017_alter_dogs_activity_level_alter_dogs_coat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='activity_level',
            field=models.CharField(choices=[('regular', 'Regular Exercise'), ('calm', 'Calm'), ('high', 'Needs Lots Of Activity'), ('energetic', 'Energetic')], default='regular', max_length=10, verbose_name='Activity Level'),
        ),
    ]
