# Generated by Django 5.1 on 2024-08-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0018_alter_dogs_activity_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogs',
            name='coat_type',
        ),
        migrations.AddField(
            model_name='dogs',
            name='coat_type',
            field=models.ManyToManyField(to='woof.coattype', verbose_name='Coat type'),
        ),
    ]
