# Generated by Django 5.2.17 on 2026-09-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("woof", "0019_temperament_dogs_temperament"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="desc_de",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_de",
            field=models.CharField(
                db_index=True, max_length=100, null=True, verbose_name="Category"
            ),
        ),
        migrations.AddField(
            model_name="coatlength",
            name="name_de",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="coattype",
            name="name_de",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="dogs",
            name="care_de",
            field=models.TextField(blank=True, null=True, verbose_name="Care"),
        ),
        migrations.AddField(
            model_name="dogs",
            name="colors_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Colors"
            ),
        ),
        migrations.AddField(
            model_name="dogs",
            name="country_de",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Country / Region of origin",
            ),
        ),
        migrations.AddField(
            model_name="dogs",
            name="height_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Height"
            ),
        ),
        migrations.AddField(
            model_name="dogs",
            name="life_expectancy_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Life expectancy"
            ),
        ),
        migrations.AddField(
            model_name="dogs",
            name="living_conditions_de",
            field=models.TextField(blank=True, null=True, verbose_name="Conditions"),
        ),
        migrations.AddField(
            model_name="dogs",
            name="photo_author_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Main photo author"
            ),
        ),
        migrations.AddField(
            model_name="dogs",
            name="summary_de",
            field=models.TextField(blank=True, null=True, verbose_name="Summary"),
        ),
        migrations.AddField(
            model_name="dogs",
            name="title_de",
            field=models.CharField(max_length=255, null=True, verbose_name="Breed"),
        ),
        migrations.AddField(
            model_name="dogs",
            name="varieties_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Varieties"
            ),
        ),
        migrations.AddField(
            model_name="dogs",
            name="weight_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Weight"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="name_de",
            field=models.CharField(max_length=100, null=True, verbose_name="Section"),
        ),
        migrations.AddField(
            model_name="temperament",
            name="name_de",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
