# Generated by Django 5.1 on 2024-08-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0019_remove_dogs_coat_type_dogs_coat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coattype',
            name='name',
            field=models.CharField(choices=[('curly', 'Curly'), ('wavy', 'Wavy'), ('rough', 'Rough-haired'), ('corded', 'Corded'), ('hairless', 'Hairless'), ('short', 'Short-haired'), ('medium', 'Medium-haired'), ('long', 'Long-haired'), ('smooth', 'Smooth-haired'), ('wiry', 'Wiry'), ('silky', 'Silky'), ('double', 'Double Coat')], max_length=20, unique=True),
        ),
    ]
