# Generated by Django 5.1 on 2024-08-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0020_alter_coattype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogs',
            name='coat_type',
        ),
        migrations.DeleteModel(
            name='CoatType',
        ),
        migrations.AddField(
            model_name='dogs',
            name='coat_type',
            field=models.CharField(choices=[('curly', 'Curly'), ('wavy', 'Wavy'), ('rough', 'Rough-haired'), ('corded', 'Corded'), ('hairless', 'Hairless'), ('short', 'Short-haired'), ('medium', 'Medium-haired'), ('long', 'Long-haired'), ('smooth', 'Smooth-haired'), ('wiry', 'Wiry'), ('silky', 'Silky'), ('double', 'Double Coat')], default='cirly', max_length=10, verbose_name='Coat type'),
        ),
    ]
