# Generated by Django 5.1 on 2024-08-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0021_remove_dogs_coat_type_delete_coattype_dogs_coat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='barking_level',
            field=models.CharField(choices=[('vocal', 'Likes To Be Vocal'), ('infrequent', 'Infrequent'), ('frequent', 'Frequent'), ('necessary', 'When Necessary'), ('medium', 'Medium')], default='vocal', max_length=20, verbose_name='Barking level'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='coat_length',
            field=models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], default='short', max_length=10, verbose_name='Coat length'),
        ),
    ]
