# Generated by Django 5.2.17 on 2026-09-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("woof", "0022_category_desc_sr_latn_category_name_sr_latn_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consent_id", models.CharField(db_index=True, max_length=64)),
                ("action", models.CharField(max_length=32)),
                ("analytics", models.BooleanField(default=False)),
                ("notice_version", models.PositiveSmallIntegerField(default=1)),
                ("page", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Consent log entry",
                "verbose_name_plural": "Consent log",
                "ordering": ["-created_at"],
            },
        ),
    ]
