# Generated by Django 5.2.17 on 2026-09-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("woof", "0023_consentlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consentlog",
            name="consent_id",
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
