# Generated by Django 5.1 on 2024-09-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woof', '0023_alter_dogs_activity_level_alter_dogs_barking_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
