"""Fill German content for Dogs, Category, Section, CoatType, CoatLength and Temperament.

Mirrors fill_ru_content.py. Idempotent: only fills empty values. Run:
    python manage.py fill_de_content
"""

from django.core.management.base import BaseCommand
from django.utils import translation

from woof.models import (
    Category,
    CoatLength,
    CoatType,
    Dogs,
    Section,
    Temperament,
)

DOGS_TITLES_DE = {
    "Afghan Hound": "Afghanischer Windhund",
    "Airedale Terrier": "Airedale-Terrier",
    "Akita": "Akita",
    "Alaskan Malamute": "Alaskan Malamute",
    "American Cocker Spaniel": "Amerikanischer Cocker Spaniel",
    "American Eskimo Dog": "Amerikanischer Eskimohund",
    "American Staffordshire Terrier": "American Staffordshire Terrier",
    "Anatolian Shepherd Dog": "Anatolischer Hirtenhund",
    "Australian Shepherd": "Australischer Schäferhund",
    "Azawakh": "Azawakh",
    "Barbado da Terceira": "Barbado da Terceira",
    "Basset Hound": "Basset Hound",
    "Bedlington Terrier": "Bedlington-Terrier",
    "Bichon Frise": "Bichon Frisé",
    "Black and Tan Coonhound": "Black and Tan Coonhound",
    "Bloodhound": "Bluthund",
    "Bolognese": "Bologneser",
    "Border Collie": "Border Collie",
    "Border Terrier": "Border Terrier",
    "Borzoi": "Borzoi",
    "Boxer": "Boxer",
    "Brussels Griffon": "Brüsseler Griffon",
    "Bulldog": "Bulldogge",
    "Bull Terrier": "Bullterrier",
    "Catahoula Leopard Dog": "Catahoula Leopard Dog",
    "Cavalier King Charles Spaniel": "Cavalier King Charles Spaniel",
    "Collie Rough": "Collie (Rauhaar)",
    "Czechoslovakian Wolfdog": "Tschechoslowakischer Wolfhund",
    "Dachshund": "Dackel",
    "Dalmatian": "Dalmatiner",
    "Dobermann": "Dobermann",
    "Drever": "Drever",
    "Dutch Shepherd Dog": "Niederländischer Schäferhund",
    "English Setter": "Englischer Setter",
    "French Bulldog": "Französische Bulldogge",
    "German Shepherd Dog": "Deutscher Schäferhund",
    "German Shorthaired Pointer": "Deutsch Kurzhaar",
    "German Spitz": "Deutscher Spitz",
    "Golden Retriever": "Golden Retriever",
    "Great Dane": "Deutsche Dogge",
    "Hovawart": "Hovawart",
    "Irish Wolfhound": "Irischer Wolfshund",
    "Italian Cane Corso": "Italienischer Cane Corso",
    "Italian Sighthound": "Italienisches Windspiel",
    "Italian Spinone": "Italienischer Spinone",
    "Kai": "Kai",
    "Keeshond (Wolfspitz)": "Keeshond (Wolfsspitz)",
    "Kleiner Münsterländer": "Kleiner Münsterländer",
    "Labrador Retriever": "Labrador Retriever",
    "Nederlandse Kooikerhondje": "Nederlandse Kooikerhondje",
    "Norwegian Elkhound Grey": "Norwegischer Elchhund (Grau)",
    "Nova Scotia Duck Tolling Retriever": "Nova Scotia Duck Tolling Retriever",
    "Old English Sheepdog": "Altenglischer Schäferhund (Bobtail)",
    "Pekingese": "Pekingese",
    "Pembroke Welsh Corgi": "Pembroke Welsh Corgi",
    "Pomeranian": "Zwergspitz (Pomeranian)",
    "Poodle": "Pudel",
    "Portuguese Podengo": "Portugiesischer Podengo",
    "Pug": "Mops",
    "Puli": "Puli",
    "Rat Terrier": "Rat Terrier",
    "Romagna Water Dog": "Lagotto Romagnolo",
    "Rottweiler": "Rottweiler",
    "Saint Bernard": "Bernhardiner",
    "Samoyed": "Samojede",
    "Scottish Terrier": "Scottish Terrier",
    "Shar Pei": "Shar Pei",
    "Shih Tzu": "Shih Tzu",
    "Siberian Husky": "Siberian Husky",
    "Sloughi": "Sloughi",
    "Treeing Walker Coonhound": "Treeing Walker Coonhound",
    "Weimaraner": "Weimaraner",
    "Whippet": "Whippet",
    "Wire Fox Terrier": "Fox Terrier (Draht)",
    "Xoloitzcuintli": "Xoloitzcuintle",
    "Yakutian Laika": "Jakutischer Laika",
    "Yorkshire Terrier": "Yorkshire Terrier",
}

CATEGORY_NAMES_DE = {
    "Breeds outside FCI classification": "Rassen außerhalb der FCI-Klassifikation",
    "Sheepdogs and Cattledogs (except Swiss Cattledogs)": "Hüte- und Treibhunde (außer Schweizer Sennenhunde)",
    "Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs": "Pinscher und Schnauzer – Molosser – Schweizer Sennenhunde und Treibhunde",
    "Terriers": "Terrier",
    "Dachshunds": "Dackel",
    "Spitz and primitive types": "Spitze und Urtyp-Rassen",
    "Scent hounds and related breeds": "Laufhunde und verwandte Rassen",
    "Pointing Dogs": "Vorstehhunde",
    "Retrievers - Flushing Dogs - Water Dogs": "Retriever – Stöberhunde – Wasserhunde",
    "Companion and Toy Dogs": "Begleit- und Toy-Hunde",
    "Sighthounds": "Windhunde",
}

SECTION_NAMES_DE = {
    "Asian Spitz and related breeds": "Asiatische Spitze und verwandte Rassen",
    "Bichons and related breeds": "Bichons und verwandte Rassen",
    "British and Irish Pointers and Setters": "Britische und irische Pointer und Setter",
    "Bull type Terriers": "Bull-Terrier",
    "Cattledogs (except Swiss Cattledogs)": "Treibhunde (außer Schweizer Sennenhunde)",
    "Chihuahueno": "Chihuahueño",
    "Continental Pointing Dogs": "Kontinentale Vorstehhunde",
    "Continental Toy Spaniel and others": "Kontinentale Toy Spaniel und andere",
    "English Toy Spaniels": "Englische Toy Spaniel",
    "European Spitz": "Europäische Spitze",
    "Flushing Dogs": "Stöberhunde",
    "Hairless Dogs": "Nackthunde",
    "Japan Chin and Pekingese": "Japan Chin und Pekingese",
    "Kromfohrländer": "Kromfohrländer",
    "Large and medium sized Terriers": "Große und mittelgroße Terrier",
    "Leash (scent) Hounds": "Schweißhunde",
    "Long-haired or fringed Sighthounds": "Langhaarige oder befranste Windhunde",
    "Molossian type": "Molosser",
    "Nordic Hunting Dogs": "Nordische Jagdhunde",
    "Nordic Sledge Dogs": "Nordische Schlittenhunde",
    "Nordic Watchdogs and Herders": "Nordische Wach- und Hütehunde",
    "Pinscher and Schnauzer type": "Pinscher und Schnauzer",
    "Poodle": "Pudel",
    "Primitive type": "Urtyp-Rassen",
    "Primitive type - Hunting Dogs": "Urtyp – Jagdhunde",
    "Recognized by Other Kennel Clubs": "Von anderen Zuchtvereinen anerkannt",
    "Related breeds": "Verwandte Rassen",
    "Retrievers": "Retriever",
    "Rough-haired Sighthounds": "Rauhaarige Windhunde",
    "Scent hounds": "Laufhunde",
    "Sheepdogs": "Hütehunde",
    "Short-haired Sighthounds": "Kurzhaarige Windhunde",
    "Single breed group (no sections)": "Einzelrassengruppe (ohne Sektionen)",
    "Small Belgian Dogs": "Kleine belgische Hunde",
    "Small Molossian type Dogs": "Kleine Molosser",
    "Small sized Terriers": "Kleine Terrier",
    "Swiss Mountain and Cattledogs": "Schweizer Sennenhunde und Treibhunde",
    "Tibetan breeds": "Tibetische Rassen",
    "Toy Terriers": "Toy-Terrier",
    "Unrecognized but Documented Breeds": "Nicht anerkannt, aber dokumentiert",
    "Water Dogs": "Wasserhunde",
}

VARIETIES_DE = {
    "Color variations": "Farbvariationen",
    "Toy, Miniature, Standard": "Toy, Zwerg, Standard",
    "Size variations": "Size variations",
    "No variations": "No variations",
    "Rabbit, Miniature, Standard": "Kaninchen, Zwerg, Standard",
    "described in «About the Breed»": "described in «About the Breed»",
    "It's a variety of German Spitz": "It's a variety of German Spitz",
    "Standard, Medium, Miniature, Toy": "Standard, Medium, Zwerg, Toy",
    "Small, Medium-sized, Large": "Small, Medium-sized, Large",
    "Standart, Intermediate, Miniature": "Standart, Intermediate, Zwerg",
}

COLORS_DE = {
    "Black, Blue, Cream, Fawn, Red, Brindle, White, Gold, Grey": "Schwarz, Blau, Creme, Falb, Rot, gestromt, Weiß, Gold, Grau",
    "Black and tan, grizzle and tan": "Schwarz-Loh, Graumeliert und Loh",
    "White, Red, Brindle, Fawn, Sesame, Piebald": "Weiß, Rot, gestromt, Falb, Sesam, Gefleckt",
    "Light gray, Black, Sable, Red, Seal, White": "Light Grau, Schwarz, Sable, Rot, Seal, Weiß",
    "Black, red, buff, brown, parti-color (white with patches), roan variations": "Schwarz, Rot, Rehfarben, Braun, Mehrfarbig (Weiß mit patches), Stichelhaarig variations",
    "White or white with cream (biscuit)": "Weiß or Weiß mit Creme (biscuit)",
    "Black, blue, fawn, red, brindle, white, solid or patched combinations": "Schwarz, Blau, Falb, Rot, gestromt, Weiß, solid or patched combinations",
    "Fawn, White, Brindle, Sable, Masked": "Falb, Weiß, gestromt, Sable, mit Maske",
    "Blue Merle, Red Merle, Black, Red, White Markings": "Blau-Merle, Rot-Merle, Schwarz, Rot, Weiß Markings",
    "Fawn, Brindle, Red, Black, Blue": "Falb, gestromt, Rot, Schwarz, Blau",
    "Yellow, gray, black, fawn, wolf-gray, often with white markings": "Gelb, Grau, Schwarz, Falb, wolfsgrau, often mit Weiß markings",
    "Tri-color, Bi-color, Lemon & White, Red & White, Tan & White": "Dreifarbig, Zweifarbig, Zitronenfarben & Weiß, Rot & Weiß, Loh & Weiß",
    "Blue, liver, sandy, blue & tan, liver & tan": "Blau, Leberfarben, sandy, Blau-Loh, Leberfarben-Loh",
    "White (sometimes with apricot, cream, or buff shadings)": "Weiß (sometimes mit Aprikosenfarben, Creme, or Rehfarben shadings)",
    "Black and tan (signature coat pattern with rich tan markings over a deep black base)": "Schwarz-Loh (signature coat pattern mit rich Loh markings over a deep Schwarz base)",
    "Black & Tan, Liver & Tan, Red": "Schwarz-Loh, Leberfarben-Loh, Rot",
    "White": "Weiß",
    "Black & white, red & white, tricolor, blue merle, sable, and other variations": "Schwarz & Weiß, Rot & Weiß, tricolor, Blau-Merle, Sable, und other variations",
    "Red, grizzle and tan, blue and tan, wheaten": "Rot, Graumeliert und Loh, Blau und Loh, wheaten",
    "White, Black, Gold, Brindle, Various combinations": "Weiß, Schwarz, Gold, gestromt, Various combinations",
    "Fawn, brindle, white markings": "Falb, gestromt, Weiß markings",
    "Red, black, black & tan, belge (reddish-brown with black mask), solid black": "Rot, Schwarz, Schwarz-Loh, belge (reddish-Braun mit Schwarz mask), solid Schwarz",
    "Fawn, Brindle, White, Piebald, Red, Fallow": "Falb, gestromt, Weiß, Gefleckt, Rot, Fallow",
    "White, Brindle, Fawn, Black, Red": "Weiß, gestromt, Falb, Schwarz, Rot",
    "Merle, blue merle, red merle, black, brindle, solid colors with patterns": "Merle, Blau-Merle, Rot-Merle, Schwarz, gestromt, solid colors mit patterns",
    "Blenheim, Tricolor, Black & Tan, Ruby": "Blenheim, Tricolor, Schwarz-Loh, Ruby",
    "Sable & White, Tricolor, Blue Merle, White, Blue Merle & White": "Sable & Weiß, Tricolor, Blau-Merle, Weiß, Blau-Merle & Weiß",
    "Yellow-gray, silver-gray, dark gray, with light mask": "Gelb-Grau, Silber-Grau, dark Grau, mit light mask",
    "Red, black & tan, chocolate & tan, cream, dapple, brindle, piebald": "Rot, Schwarz-Loh, Schokoladenbraun & Loh, Creme, Gefleckt, gestromt, Gefleckt",
    "White with black or liver spots, White & Orange, White & Lemon, White Black & Tan": "Weiß mit Schwarz or Leberfarben spots, Weiß & Orange, Weiß & Zitronenfarben, Weiß Schwarz-Loh",
    "Black & Rust, Red & Rust, Blue & Rust, Fawn & Rust, White": "Schwarz & Rust, Rot & Rust, Blau & Rust, Falb & Rust, Weiß",
    "Yellow, Fawn, Black & Tan": "Gelb, Falb, Schwarz-Loh",
    "Brindle (gold or silver), sometimes with black patterning": "gestromt (Gold or Silber), sometimes mit Schwarz patterning",
    "Blue Belton, Lemon Belton, Orange Belton, Tricolor": "Blau Belton, Zitronenfarben Belton, Orange Belton, Tricolor",
    "Brindle, Fawn, White, Pied, Cream": "gestromt, Falb, Weiß, Gefleckt, Creme",
    "Black and tan, black and red, sable, solid black, black and cream, black and silver": "Schwarz-Loh, Schwarz und Rot, Sable, solid Schwarz, Schwarz und Creme, Schwarz und Silber",
    "Liver, Liver & White, Roan": "Leberfarben, Leberfarben & Weiß, Stichelhaarig",
    "Black, white, cream, brown, orange, sable": "Schwarz, Weiß, Creme, Braun, Orange, Sable",
    "Golden shades (light to dark)": "Golden shades (light to dark)",
    "Fawn, Brindle, Blue, Black, Harlequin, Mantle": "Falb, gestromt, Blau, Schwarz, Harlequin, Mantle",
    "Black, black and gold, blonde": "Schwarz, Schwarz und Gold, blonde",
    "Gray, Brindle, Red, Black, Fawn, White": "Grau, gestromt, Rot, Schwarz, Falb, Weiß",
    "Black, Gray, Fawn, Red, Brindle": "Schwarz, Grau, Falb, Rot, gestromt",
    "Fawn, Blue, Black, Red, White, Cream": "Falb, Blau, Schwarz, Rot, Weiß, Creme",
    "White, white & orange, orange roan, white & brown, brown roan": "Weiß, Weiß & Orange, Orange Stichelhaarig, Weiß & Braun, Braun Stichelhaarig",
    "Tiger brindle (brown/black stripes)": "Tiger gestromt (Braun/Schwarz stripes)",
    "Grey with black shading, cream, variations of wolf-grey": "Grau mit Schwarz shading, Creme, variations of Wolf-Grau",
    "Brown & white, brown roan": "Braun & Weiß, Braun Stichelhaarig",
    "Black, Yellow, Chocolate": "Schwarz, Gelb, Schokoladenbraun",
    "White with orange-red patches": "Weiß mit Orange-Rot patches",
    "Gray, Black-tipped": "Grau, Schwarz-tipped",
    "Shades of red and orange with white markings often present on chest, feet, tail tip, or face": "Shades of Rot und Orange mit Weiß markings often present on chest, feet, tail tip, or face",
    "Gray & White, Blue & White, Blue Merle, Grizzle & White": "Grau & Weiß, Blau & Weiß, Blau-Merle, Graumeliert & Weiß",
    "Gold, red, sable, cream, black, black & tan, parti-color": "Gold, Rot, Sable, Creme, Schwarz, Schwarz-Loh, Mehrfarbig",
    "Red, Sable, Fawn, Black & Tan, Tricolor": "Rot, Sable, Falb, Schwarz-Loh, Tricolor",
    "Orange, Black, White, Cream, Blue, Brown, Sable, Chocolate Merle, Brindle, Beaver": "Orange, Schwarz, Weiß, Creme, Blau, Braun, Sable, Schokoladenbraun Merle, gestromt, Beaver",
    "Black, white, brown, apricot, red, silver, cream, gray, blue, parti-color": "Schwarz, Weiß, Braun, Aprikosenfarben, Rot, Silber, Creme, Grau, Blau, Mehrfarbig",
    "Yellow, Fawn, Chestnut, Gray, Gold, Red, Orange and mixed": "Gelb, Falb, Chestnut, Grau, Gold, Rot, Orange und mixed",
    "Fawn, Black, Apricot, Silver Fawn": "Falb, Schwarz, Aprikosenfarben, Silber Falb",
    "Black, Gray, White": "Schwarz, Grau, Weiß",
    "Black, white, tan, chocolate, blue, lemon, red; bicolor and tricolor patterns": "Schwarz, Weiß, Loh, Schokoladenbraun, Blau, Zitronenfarben, Rot; bicolor und tricolor patterns",
    "Off-white, white with orange or brown patches, brown, orange, roan": "Off-Weiß, Weiß mit Orange or Braun patches, Braun, Orange, Stichelhaarig",
    "Black & Rust, Black & Mahogany, Black & Tan": "Schwarz & Rust, Schwarz & Mahogany, Schwarz-Loh",
    "Red & White, Brindle & White, Mostly White": "Rot & Weiß, gestromt & Weiß, Mostly Weiß",
    "White, Cream, Biscuit": "Weiß, Creme, Biscuit",
    "Black, Brindle, Wheaten, Silver Brindle": "Schwarz, gestromt, Wheaten, Silber gestromt",
    "Solid colors: cream, red, fawn, black, blue, chocolate, sable": "Solid colors: Creme, Rot, Falb, Schwarz, Blau, Schokoladenbraun, Sable",
    "Black, White, Gold, Brindle, Liver, Silver, Mixed": "Schwarz, Weiß, Gold, gestromt, Leberfarben, Silber, Mixed",
    "Black & White, Gray & White, Red & White, Agouti, All-White": "Schwarz & Weiß, Grau & Weiß, Rot & Weiß, Agouti, All-Weiß",
    "Cream, sand, red fawn, mahogany, brindle, black mask, black ears, with or without small white markings": "Creme, sand, Rot Falb, mahogany, gestromt, Schwarz mask, Schwarz ears, mit or without small Weiß markings",
    "Tricolor (Black, White, Tan)": "Tricolor (Schwarz, Weiß, Loh)",
    "Silver gray, Blue, Gray": "Silber Grau, Blau, Grau",
    "Fawn, Brindle, Black, Blue, Red, White, Mixed": "Falb, gestromt, Schwarz, Blau, Rot, Weiß, Mixed",
    "White with black or brown markings": "Weiß mit Schwarz or Braun markings",
    "Black, gray, slate, red, bronze, liver, solid or spotted": "Schwarz, Grau, slate, Rot, bronze, Leberfarben, solid or spotted",
    "White, black, brown, gray, piebald / tricolor combinations": "Weiß, Schwarz, Braun, Grau, Gefleckt / tricolor combinations",
    "Steel blue & Tan": "Steel Blau-Loh",
}

COUNTRY_DE = {
    "Afganistan": "Afghanistan",
    "Great Britain": "Großbritannien",
    "Japan": "Japan",
    "USA": "USA",
    "Germany": "Deutschland",
    "Turkey": "Türkei",
    "Mali": "Mali",
    "Portugal": "Portugal",
    "Belgium, France": "Belgien, Frankreich",
    "Belgium": "Belgien",
    "Italy": "Italien",
    "Russian Federation": "Russlandn Federation",
    "Czechoslovakia": "Tschechoslowakei",
    "Croatia": "Kroatien",
    "Sweden": "Schweden",
    "The Netherlands": "The Niederlande",
    "France": "Frankreich",
    "Irleand": "Irland",
    "Norway": "Norwegen",
    "Canada": "Kanada",
    "China": "China",
    "Hungary": "Ungarn",
    "Switzerland": "Schweiz",
    "Northern Russia, Siberia": "Northern Russland, Sibirien",
    "Tibet (China)": "Tibet (China)",
    "Morocco": "Marokko",
    "Mexico": "Mexiko",
}

COATTYPE_DE = {
    "Curly": "Lockig",
    "Wavy": "Gewellt",
    "Corded": "Geschnürt",
    "Hairless": "Nackt",
    "Smooth": "Kurzhaar",
    "Double coat": "Doppeltes Fell",
    "Silky": "Seidig",
    "Rough": "Rauhaarig",
    "Wiry": "Drahtig",
}

COATLEN_DE = {
    "Short": "Kurz",
    "Medium": "Mittel",
    "Long": "Lang",
}

TEMPERAMENT_DE = {
    "Alert": "Aufmerksam",
    "Inquisitive": "Neugierig",
    "Loving": "Liebevoll",
    "Determined": "Entschlossen",
    "Confident": "Selbstbewusst",
    "Good-natured": "Gutmütig",
    "Charming": "Charmant",
    "Courageous": "Mutig",
    "Protective": "Schützend",
    "Calm": "Gelassen",
    "Energetic": "Energiegeladen",
    "Reserved": "Zurückhaltend",
    "Fast": "Schnell",
    "Hardworking": "Fleißig",
    "Patient": "Geduldig",
    "Laid-back": "Locker",
    "Spirited": "Temperamentvoll",
    "Easygoing": "Unkompliziert",
    "Devoted": "Hingebungsvoll",
    "Eager": "Eifrig",
    "Focused": "Fokussiert",
    "Game": "Spielmutig",
    "Plucky": "Mutig",
    "Quiet": "Ruhig",
    "Self-important": "Selbstgewiss",
    "Stubborn": "Stur",
    "Social": "Gesellig",
    "Active": "Aktiv",
    "Fearless": "Furchtlos",
    "Hardy": "Robust",
    "Aloof": "Distanziert",
    "Persistent": "Beharrlich",
    "Independent": "Unabhängig",
    "Even-tempered": "Ausgeglichen",
    "Adaptable": "Anpassungsfähig",
    "Smart": "Klug",
    "Dignified": "Würdevoll",
    "Sensitive": "Sensibel",
    "Sociable": "Kontaktfreudig",
    "Trainable": "Trainierbar",
    "Playful": "Verspielt",
    "Brave": "Tapfer",
    "Friendly": "Freundlich",
    "Intelligent": "Intelligent",
    "Happy": "Fröhlich",
    "Loyal": "Loyal",
    "Outgoing": "Aufgeschlossen",
    "Affectionate": "Zärtlich",
    "Agile": "Agil",
    "Strong-willed": "Willensstark",
    "Gentle": "Sanft",
    "Cheerful": "Fröhlich",
}


class Command(BaseCommand):
    help = "Fill German names and short traits for dogs, categories, sections and vocabularies."

    def handle(self, *args, **options):
        with translation.override("de"):
            dog_updated = 0
            for dog in Dogs.objects.all():
                de = DOGS_TITLES_DE.get(dog.title)
                if de and not dog.title_de:
                    dog.title_de = de
                    dog.save(update_fields=["title_de"])
                    dog_updated += 1
            self.stdout.write(f"Dogs.title_de filled: {dog_updated}")

            for model, fname, mapping in (
                (Category, "name_de", CATEGORY_NAMES_DE),
                (Section, "name_de", SECTION_NAMES_DE),
                (CoatType, "name_de", COATTYPE_DE),
                (CoatLength, "name_de", COATLEN_DE),
                (Temperament, "name_de", TEMPERAMENT_DE),
            ):
                updated = 0
                for obj in model.objects.all():
                    de = mapping.get(obj.name)
                    if de and not getattr(obj, fname):
                        setattr(obj, fname, de)
                        obj.save(update_fields=[fname])
                        updated += 1
                self.stdout.write(f"{model.__name__}.{fname} filled: {updated}")

            short_updates = {
                "varieties_de": VARIETIES_DE,
                "country_de": COUNTRY_DE,
                "colors_de": COLORS_DE,
            }
            for fname, mapping in short_updates.items():
                count = 0
                for dog in Dogs.objects.all():
                    en = getattr(dog, fname[:-3])
                    de = mapping.get(en)
                    if de and not getattr(dog, fname):
                        setattr(dog, fname, de)
                        dog.save(update_fields=[fname])
                        count += 1
                self.stdout.write(f"Dogs.{fname} filled: {count}")
